version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgresDb:
        condition: service_started
    restart: on-failure:3
    networks:
      app-network:
    environment:
      SPRING_DATABASE_NAME: ${SPRING_DATABASE_NAME}
      SPRING_DATABASE_USER: ${SPRING_DATABASE_USER}
      SPRING_DATABASE_PASSWORD: ${SPRING_DATABASE_PASSWORD}
      SPRING_DATABASE_URL: jdbc:postgresql://postgresDb:5432/Spring

  postgresDb:
    image: postgres:16.0
    ports:
      - "5432:5432"
    restart: always
    env_file: .env
    networks:
      app-network:
    environment:
      POSTGRES_PASSWORD: ${SPRING_DATABASE_PASSWORD}
      POSTGRES_USER: ${SPRING_DATABASE_USER}
      POSTGRES_DB: ${SPRING_DATABASE_NAME}

networks:
  app-network: